version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Restore Packages
          command: dotnet restore
      - run:
          name: Build App
          command: dotnet build -c Release
      - run:
          name: Run Tests
          command: dotnet test
      - run:
          name: Build nuget packages
          command: dotnet pack -c Release
      - store_artifacts:
          path: "/root/project/src/CompressedStaticFiles/bin/Release/"
